a = input('Digite algo')
print('O tipo primitivo desse valor é ', type(a))
print('Só tem espaço ', a.isspace())
print('É um número ', a.isnumeric())
print('É alfabético ', a.isalpha())
print('É alphanúmero ', a.isalnum())
print('Maiscúla ', a.isupper())
print('Minuscúla', a.islower())
print('Capitalizada', a.istitle())