nome = str(input('Digite seu nome completo')).strip()
upper = nome.upper()
lower = nome.lower()
cont = len(nome) - nome.count(' ')
separa = nome.split()

print('Seu nome em maiúsculo é {}'.format(upper))
print('Seu nome em minuscúlo é {}'.format(lower))
print('Seu nome tem ao todo {} letras'.format(cont))
print('Seu primeiro nome é {} e ele tem {} letras'.format(separa[0], len(separa[0])))